# Generated by Django 3.2.1 on 2021-05-10 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название песни')),
                ('age', models.DateField(default=datetime.timedelta(0), verbose_name='Дата выпуска')),
                ('image', models.ImageField(upload_to='songs/', verbose_name='Изображение')),
                ('artist', models.CharField(max_length=50, verbose_name='Исполнитель')),
                ('album', models.CharField(max_length=70, verbose_name='Альбом')),
                ('ganre', models.CharField(max_length=70, verbose_name='Жанр')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
    ]
