# Generated by Django 3.2.1 on 2021-05-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='songs_posters/', verbose_name='Изображение'),
        ),
    ]
