# Generated by Django 3.2.2 on 2021-05-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(null=True, upload_to='songs_audio/', verbose_name='Песня'),
        ),
    ]
