# Generated by Django 3.2.2 on 2021-05-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20210520_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_image/', verbose_name='Изображение'),
        ),
    ]
